# General parameters
seed: [0, 10, 20]
num_cpu: 4
datestamp: True
data_dir: 'runs/test'

# Environment loop parameters
epochs: 20
steps_per_epoch: 50  # number of interaction steps (state-action paris) for agent and env in each epoch
max_ep_len: 50  # max length of trajectory 
save_freq: 10

num_envs: 4  # should be same num_cpu/num_workers

env_kwargs:
  - - benchmark: 'opengm'
      filepath: 'data/seg-3d-300/graphs/gm_knott_3d_074.npy'
      proposal_solver: 'multicut_gaec'
      subroutine_solver: 'multicut_gaec'
      num_steps: 10
    - benchmark: 'opengm'
      filepath: 'data/seg-3d-300/graphs/gm_knott_3d_074.npy'
      proposal_solver: 'multicut_gaec'
      subroutine_solver: 'multicut_gaec'
      num_steps: 10
    - benchmark: 'opengm'
      filepath: 'data/seg-3d-300/graphs/gm_knott_3d_074.npy'
      proposal_solver: 'multicut_gaec'
      subroutine_solver: 'multicut_gaec'
      num_steps: 10
    - benchmark: 'opengm'
      filepath: 'data/seg-3d-300/graphs/gm_knott_3d_074.npy'
      proposal_solver: 'multicut_gaec'
      subroutine_solver: 'multicut_gaec'
      num_steps: 10
 
  # io_function: 'load_single_opengm_benchmark_graph'
  # filepath: 'data/seg-3d-300/graphs/gm_knott_3d_074.npy'
  # proposal_solver: 'multicut_gaec'
  # subroutine_solver: 'multicut_gaec'
  # num_steps: 10  # Number of steps until env termination

agent:
  - train_critic_iters: 80
    train_policy_iters: 80
    clip_ratio: 0.2
    target_kl: 0.05
    batch_size: 10

rollout_buffer:
  - discount: 0.99
    lam: 0.97

mu_network:
  name: 'PolicyGCN'
  kwargs:
    in_channels: 2
    hidden_channels: 146
    out_channels: 146
    num_layers: 4
    dropout: 0.0
    batch_norm: true
    residual: true
    mlp_in_channels: 146
    mlp_hidden_channels: [73]
    mlp_out_channels: 1

variance_network:
  name: 'PolicyGCN'
  kwargs:
    in_channels: 2
    hidden_channels: 146
    out_channels: 146
    num_layers: 4
    dropout: 0.0
    batch_norm: true
    residual: true
    mlp_in_channels: 146
    mlp_hidden_channels: [73]
    mlp_out_channels: 1

critic_network:
  name: 'ValueGCN'
  kwargs:
    in_channels: 2
    hidden_channels: 146
    out_channels: 146
    num_layers: 4
    dropout: 0.0
    batch_norm: true
    residual: true
    readout: 'mean'
    mlp_in_channels: 146
    mlp_hidden_channels: [73]
    mlp_out_channels: 1
 
mu_optimizer:
  name: 'Adam'
  kwargs:
    lr: 0.000001  # 3e-5
    weight_decay: 0.0001

variance_optimizer:
  name: 'Adam'
  kwargs:
    lr: 0.000001  # 3e-5
    weight_decay: 0.0001

critic_optimizer:
  name: 'Adam'
  kwargs:
    lr: 0.001  # 1e-3
